parameters:
    wa72_jsonrpc.jsonrpccontroller.class: Wa72\JsonRpcBundle\Controller\JsonRpcController

services:
    wa72_jsonrpc.jsonrpccontroller:
        public: true
        class: '%wa72_jsonrpc.jsonrpccontroller.class%'
        arguments: ['@service_container', '%wa72.jsonrpc%']
